apiVersion: v1
kind: Namespace
metadata:
  name: compliant

---
apiVersion: v1
kind: Pod
metadata:
  name: compliant-pod
  namespace: compliant
spec:
  containers:
  - image: busybox
    name: compliant-pod
